data <- read.table("household_power_consumption.txt", sep=";", skip=66637, nrows=2880)
names(data) <- names(read.csv("household_power_consumption.txt", sep=";",nrows=1))
data$DateTime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S",)

png("plot3.png", width = 480, height = 480, units="px", bg = "transparent")
plot(data$DateTime,data$Sub_metering_1, type='l', ylab="Energy sub metering", xlab="")
lines(data$DateTime,data$Sub_metering_2, type='l', col="red")
lines(data$DateTime,data$Sub_metering_3, type='l', col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black", "red", "blue"), lty = 1,  pch = NA)
dev.off()
